In [1]:
import numpy as np
import pandas as pd
from datetime import datetime

In [42]:
songs_data = pd.read_csv('songs_data.tsv', sep='\t')

In [43]:
songs_data.head()

,id,name,artist,followers,artist popularity,markets,album,release date,duration,explicit,local,popularity
0,2BgEsaKNfHUdlh97KmvFyo,2002,Anne-Marie,10171858,76,183,Speak Your Mind (Deluxe),2018-04-27,186986,False,False,81
1,53JDP7TaGacjUtnStYQp51,CƠN MƯA NGANG QUA - REMIX 2022,Sơn Tùng M-TP,3789324,57,183,CƠN MƯA NGANG QUA (REMIX 2022),2022-06-07,236716,False,False,45
2,2zYc8JUkCUqY7r567OzpUc,Replay trên con Guây,"Phuc Du,Đan Ni","15726,5","46,36",183,Replay trên con Guây,2022-10-10,221607,False,False,54
3,3TSLqZssCoCdDlMhCJ08XW,Still Life,BIGBANG,4931939,64,182,Still Life,2022-04-05,188369,False,False,66
4,0IGUXY4JbK18bu9oD4mPIm,TOMBOY,(G)I-DLE,4223918,74,181,I NEVER DIE,2022-03-14,174386,False,False,79

In [62]:
data_np = np.array(songs_data)

for i in range(len(data_np)):
    data_np[i][2] = data_np[i][2].split(',')
    data_np[i][3] = list(map(int, data_np[i][3].split(',')))
    data_np[i][4] = list(map(int, data_np[i][4].split(',')))
    data_np[i][5] = int(data_np[i][5])
    data_np[i][7] = datetime.strptime(data_np[i][7], '%Y-%m-%d')
    data_np[i][8] = int(data_np[i][8])
    data_np[i][9] = 0 if data_np[i][9] == 'False' else 1
    data_np[i][10] = 0 if data_np[i][10] == 'False' else 1
    data_np[i][11] = int(data_np[i][11])

In [64]:
max = 0
idx = 0
for i in data_np:
    if len(i[2]) > max:
        max = len(i[2])
        idx = i
max, idx

(10,
 array(['2iyjgym6md4p6RazSVF4qx', '2022',
        list(['Henry Follett', 'DJ Pink Tang', 'Daniel Copestake', 'Henry Follett Media', 'Hnetsierra UK', 'Ultramobile UK', 'hjfollett', 'DJ TikTok', 'Chicken Nugget Man', 'Samuel Moffat-Yeates']),
        list([145, 2, 3, 0, 0, 0, 0, 369619, 273, 1]),
        list([1, 0, 0, 0, 0, 0, 0, 36, 11, 0]), 183, '2022',
        datetime.datetime(2022, 2, 4, 0, 0), 70452, 1, 1, 6], dtype=object))

In [38]:
songs_train = songs_data.iloc[50:]
songs_test = songs_data.iloc[:50]

In [24]:
train_features = songs_train.iloc[:, :-1]
train_label = songs_train.iloc[:, -1]
test_features = songs_test.iloc[:, :-1]
test_label = songs_test.iloc[:, -1]

In [25]:
train_features.head()

,id,name,artist,followers,artist popularity,markets,album,release date,duration,explicit,local
50,0V3wPSX9ygBnCm8psDIegu,Anti-Hero,['Taylor Swift'],[61488932],[100],182,Midnights,2022-10-21,200690,False,False
51,2pIUpMhHL6L9Z5lnKxJJr9,Attention,['NewJeans'],[850212],[74],183,NewJeans 1st EP 'New Jeans',2022-08-01,180066,False,False
52,5quFr5s5PXYfUX5jV2EBZ1,GANADARA (Feat. IU),"['Jay Park', 'IU']","[1813621, 7487441]","[65, 70]",183,GANADARA,2022-03-11,203727,False,False
53,7EyhPjrJzjx0fk2i7vUJCS,Pink Venom,['BLACKPINK'],[34043383],[86],54,Pink Venom,2022-08-19,186964,False,False
54,0Q5VnK2DYzRyfqQRJuUtvi,LOVE DIVE,['IVE'],[1320894],[73],183,LOVE DIVE,2022-04-05,177186,False,False

In [26]:
pd.DataFrame(train_label).head()

    popularity
50          96
51          85
52          67
53          81
54          83

In [27]:
test_features.head()

,id,name,artist,followers,artist popularity,markets,album,release date,duration,explicit,local
0,2BgEsaKNfHUdlh97KmvFyo,2002,['Anne-Marie'],[10171858],[76],183,Speak Your Mind (Deluxe),2018-04-27,186986,False,False
1,3gZyjgWdEibTsQFEmGiSSk,2022 World Championship Theme,['League of Legends'],[1513919],[78],183,2022 World Championship Theme,2022-09-07,205500,False,False
2,45sv69N1tMsztMhOj6yhfz,2022 Tanging Ain't Dead Cypher,['Dre Cannon Music'],[186],[29],183,2022 Tanging Ain't Dead Cypher,2022-02-21,139088,False,False
3,3TSLqZssCoCdDlMhCJ08XW,Still Life,['BIGBANG'],[4931939],[64],182,Still Life,2022-04-05,188369,False,False
4,5aucVLKiumD89mxVCB4zvS,Rush Hour (Feat. j-hope of BTS),"['Crush', 'j-hope']","[1049290, 12264878]","[68, 73]",180,Rush Hour,2022-09-22,177302,False,False

In [28]:
pd.DataFrame(test_label).head()

   popularity
0          81
1          51
2          47
3          66
4          80

In [ ]:
# for i in range(len(songs_data)):
    # songs_data.iloc[i, 2] = songs_data.iloc[i, 2].split(',') if ',' in songs_data.iloc[i, 2] else [songs_data.iloc[i, 2]]
    # songs_data.iloc[i, 3] = list(map(int, songs_data.iloc[i, 3].split(','))) if ',' in songs_data.iloc[i, 3] else list(int(songs_data.iloc[i, 3]))
    # songs_data.iloc[i, 4] = list(map(int, songs_data.iloc[i, 4].split(','))) if ',' in songs_data.iloc[i, 4] else list(int(songs_data.iloc[i, 4]))
    # songs_data.iloc[i, 5] = int(songs_data.iloc[i, 5])
    # songs_data.iloc[i, 7] = datetime.strptime(songs_data.iloc[i, 7], '%Y-%m-%d')
    # songs_data.iloc[i, 8] = int(songs_data.iloc[i, 8])
    # songs_data.iloc[i, 9] = 0 if songs_data.iloc[i, 9] == 'False' else 1
    # songs_data.iloc[i, 10] = 0 if songs_data.iloc[i, 10] == 'False' else 1
    # songs_data.iloc[i, 11] = int(songs_data.iloc[i, 11])

# songs_data.iloc[9, 2] = ['Crush', 'jhope']