In [85]:
import numpy as np
import pandas as pd
from datetime import datetime

In [89]:
raw_data = pd.read_csv('songs_data.tsv', sep='\t')
raw_data.head()

,id,name,artist,genres,followers,artist popularity,markets,album,release date,album popularity,duration,explicit,popularity
0,2BgEsaKNfHUdlh97KmvFyo,2002,Anne-Marie,"dance pop,pop,pop dance,post-teen pop,tropical...",10179165,76,183,Speak Your Mind (Deluxe),2018-04-27,72,186986,False,81
1,4Pbg79cTBu4vgSphoyNq3j,2002,Anne-Marie,"dance pop,pop,pop dance,post-teen pop,tropical...",10179165,76,183,2002,2018-04-19,52,186986,False,63
2,2zYc8JUkCUqY7r567OzpUc,Replay trên con Guây,"Phuc Du,Đan Ni",v-pop,"15757,5","46,36",183,Replay trên con Guây,2022-10-10,43,221607,False,54
3,3gZyjgWdEibTsQFEmGiSSk,2022 World Championship Theme,League of Legends,"speedrun,video game music",1515248,78,183,2022 World Championship Theme,2022-09-07,40,205500,False,52
4,5aucVLKiumD89mxVCB4zvS,Rush Hour (Feat. j-hope of BTS),"Crush,j-hope","k-pop,korean r&b,k-pop,k-rap","1049749,12281987","67,73",180,Rush Hour,2022-09-22,69,177302,False,80

In [108]:
data_np = np.array(raw_data)

for i in range(len(data_np)):
    data_np[i][2] = data_np[i][2].split(',')
    data_np[i][3] = data_np[i][3].split(',') if type(data_np[i][3]) != float else ['Untitled']
    data_np[i][4] = list(map(int, data_np[i][4].split(',')))
    data_np[i][5] = list(map(int, data_np[i][5].split(',')))
    data_np[i][6] = int(data_np[i][6])
    data_np[i][8] = datetime.strptime(data_np[i][8], '%Y-%m-%d')
    data_np[i][9] = int(data_np[i][9])
    data_np[i][10] = int(data_np[i][10])
    data_np[i][11] = 0 if data_np[i][11] == 'False' else 1
    data_np[i][12] = int(data_np[i][12])

In [91]:
songs_data = pd.DataFrame(data_np, columns=raw_data.columns)
songs_data.head()

,id,name,artist,genres,followers,artist popularity,markets,album,release date,album popularity,duration,explicit,popularity
0,2BgEsaKNfHUdlh97KmvFyo,2002,[Anne-Marie],"[dance pop, pop, pop dance, post-teen pop, tro...",[10179165],[76],183,Speak Your Mind (Deluxe),2018-04-27,72,186986,1,81
1,4Pbg79cTBu4vgSphoyNq3j,2002,[Anne-Marie],"[dance pop, pop, pop dance, post-teen pop, tro...",[10179165],[76],183,2002,2018-04-19,52,186986,1,63
2,2zYc8JUkCUqY7r567OzpUc,Replay trên con Guây,"[Phuc Du, Đan Ni]",[v-pop],"[15757, 5]","[46, 36]",183,Replay trên con Guây,2022-10-10,43,221607,1,54
3,3gZyjgWdEibTsQFEmGiSSk,2022 World Championship Theme,[League of Legends],"[speedrun, video game music]",[1515248],[78],183,2022 World Championship Theme,2022-09-07,40,205500,1,52
4,5aucVLKiumD89mxVCB4zvS,Rush Hour (Feat. j-hope of BTS),"[Crush, j-hope]","[k-pop, korean r&b, k-pop, k-rap]","[1049749, 12281987]","[67, 73]",180,Rush Hour,2022-09-22,69,177302,1,80

In [101]:
def powerOfTwo(n):
    return n**2

In [106]:
data_np_copy = np.copy(data_np)

for i in range(len(data_np_copy)):
    data_np_copy[i][4] = int(np.sqrt(np.sum(list(map(powerOfTwo, data_np_copy[i][4])))))
    data_np_copy[i][5] = int(np.sqrt(np.sum(list(map(powerOfTwo, data_np_copy[i][5])))))

standard_data = np.array([[col for col in line if type(col) == int] for line in data_np_copy])

In [105]:
model_data = pd.DataFrame(standard_data, columns=['followers', 'artist popularity', 'markets', 'album popularity', 'duration', 'explicit', 'popularity'])
model_data.head()

,followers,artist popularity,markets,album popularity,duration,explicit,popularity
0,10179165,76,183,72,186986,1,81
1,10179165,76,183,52,186986,1,63
2,15757,58,183,43,221607,1,54
3,1515248,78,183,40,205500,1,52
4,12326766,99,180,69,177302,1,80

In [109]:
songs_train = model_data.iloc[50:]
songs_test = model_data.iloc[:50]

train_features = model_data.iloc[:, :-1]
train_label = model_data.iloc[:, -1]
test_features = model_data.iloc[:, :-1]
test_label = model_data.iloc[:, -1]

In [110]:
train_features.head()

   followers  artist popularity  markets  album popularity  duration  explicit
0   10179165                 76      183                72    186986         1
1   10179165                 76      183                52    186986         1
2      15757                 58      183                43    221607         1
3    1515248                 78      183                40    205500         1
4   12326766                 99      180                69    177302         1

In [111]:
pd.DataFrame(train_label).head()

   popularity
0          81
1          63
2          54
3          52
4          80

In [112]:
test_features.head()

   followers  artist popularity  markets  album popularity  duration  explicit
0   10179165                 76      183                72    186986         1
1   10179165                 76      183                52    186986         1
2      15757                 58      183                43    221607         1
3    1515248                 78      183                40    205500         1
4   12326766                 99      180                69    177302         1

In [113]:
pd.DataFrame(test_label).head()

   popularity
0          81
1          63
2          54
3          52
4          80

In [115]:
# query maximum number of artists in 1 song
max_artist = 0
idx = 0
for i in range(len(data_np)):
    if len(data_np[i][2]) > max_artist:
        max_artist = len(data_np[i][2])
        idx = i
max_artist, idx

(10, 221)